### ISSUE TITLE
LInk rendering problem on slide #14 "solving the first snag"

### ISSUE THREAD

**Issue by ianschmutte** [labordynamicsinstitute/replication-tutorial-2019#2]
![image](https://user-images.githubusercontent.com/6665426/56664007-5254b280-6675-11e9-9d75-d6ef2c23e82c.png)

**Comment by larsvilhuber** [comment]
Hm. these render fine in the IDE. Wonder why it's not working in the "wild"...

Thanks.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________
